name: Epiphany Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:

    name: Run Epiphany tests on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Epiphany Browser
      run: sudo apt-get install epiphany-browser

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests with XVFB
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm run test:epiphany
