name: MacOS Tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Mac OS tests
    runs-on: macos-latest
    strategy:
      matrix:
        node: [16, 18]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:macos
