name: Playwright Tests on macos-latest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run Playwright tests
    runs-on: macos-latest

    strategy:
      matrix:
        node: [18, 20]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Setup Playwright
        run: npx playwright install

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test
