name: Playwright Tests on ubuntu-latest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run Playwright tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 18]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Update packages
        run: sudo apt-get update

      - name: Setup Playwright
        run: npx playwright install-deps

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with XVFB
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test
