name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run Playwright tests
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 2
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: [16, 18]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Playwright
        run: npx playwright install-deps

      - name: Install dependencies
        run: npm ci

      if: ${{ matrix.os }} == 'ubuntu-latest'
        - name: Run unit tests with XVFB
          uses: GabrielBB/xvfb-action@v1
          with:
            run: npm run test

      if: ${{ matrix.os }} != 'ubuntu-latest'
        - name: Run unit tests
          run: npm run test
